### ISSUE TITLE
Novo plano de estudos - AWS Certified Developer Associate 

### ISSUE THREAD

**Issue by normandesjuniorzup** [zup-academy/planos-estudos-zup#1]
## Como usar este plano?

Este plano é um guia criado por um Zupper que obteve a certificação AWS Certified Developer Associate, aqui estão os passos seguidos por ele para obter o conhecimento e prática para passar no exame.

Existem links para cursos e material para simulados que são pagos, mas que o investimento vale a pena pois vai facilitar a compreensão do conteúdo e da dinâmica da prova.

## Passos do plano em si

1. Descrição do motivo que explica a importância do plano:

Se você chegou neste plano é porque já sabe da importância de Cloud nos dias atuais, e a AWS é uma das mais relevantes no mundo, quanto mais conhecimento adquirir melhor será sua contribuição em projetos que usam AWS.

2. Objetivo de aprendizagem conectado com nível 3 da taxonomia de bloom:

Ao concluir o plano de estudos, a pessoa será capaz de aplicar diversos serviços AWS na prática como um desenvolvedor de aplicações para Cloud, indentificando e sugerindo as melhores formas tanto em relação a performance quanto custo para as aplicações.

E caso ainda faça a prova oficial e passe no exame, a certificação irá dar uma notoriedade maior para a carreira do desenvolvedor.

3. Pré-requisitos necessários para seguir o plano:

Conhecimento básico de cloud, experiência como desenvolvedor de software em pelo menos uma linguagem de programação e alguma experiência prévia com a AWS.

4. Lista de objetivos de aprendizagem conectados com o nível 3 da taxonomia de bloom:

* Demonstrar conhecimento e compreensão dos principais produtos da AWS
* Usar e sugerir práticas recomendadas de arquitetura da AWS 
* Demonstrar confiança no desenvolvimento, implantação e resolução de aplicações em nuvem usando AWS
* Fornecer mais confiança e credibilidade ao desenvolvedor

5.  Lista de temas que serão abordados no plano, com referências e objetivos de aprendizagem específicos:

* Página oficial [AWS Certified Developer Associate](https://aws.amazon.com/pt/certification/certified-developer-associate/?ch=sec&sec=rmg&d=1)

* Curso na [Udemy do Stephane Maarek](https://www.udemy.com/share/101WES3@Icb4aoobsnBm4BNyJvxojlCjzAhhc79BkDDjeb-wdDr81K5OdWi9ZvP0ntPK6TA=/)
	
	* Objetivo: o curso aborda a parte teórica e com demonstrações práticas de TODOS os serviços necessários para passar na prova.

* Simulado na [Whizlabs](https://www.whizlabs.com/)

	* Objetivo: depois de concluir o curso na Udemy é extremamente recomendado que faça pelo menos 5 Practice Test da Whizlabs para esta prova.

* Marcar a prova

	* Objetivo: colocar a prova o que foi estudado/treinado. Agora é o momento de marcar a prova e tirar a certificação.	

6. Lista de palavras chave:
aws, certificação, cloud, developer associate

7.  Exercícios que permitem a pessoa treinar o que ela estudou:

* Realizar os hands on feitos pelo Stephane Maarek no curso junto com ele para garantir que entendeu todo o processo

* Realizar pelo menos 5 Practice Test na Whizlabs e rever o conteúdo quando necessário principalmente nas questões que errar

**Comment by jacksonmotazup** [comment]
Boa tarde!
O plano foi postado na plataforma, segue o link:
https://handora.zup.com.br/plano-de-estudos/59
Muito obrigado pela contribuição!
